### ISSUE TITLE
Update to Ruby 2.7.1

### ISSUE THREAD

**Issue by ukolovda** [tobiashm/ruby-instantclient#2]
Hello!

Can you update and publish for Ruby 2.7.1 (and other latest versions), please?

Thank you!

**Comment by tobiashm** [comment]
@ukolovda sorry for the late response, but there should be updated images with the newest Ruby versions up on Docker Hub now. See https://hub.docker.com/repository/docker/tobiashm/ruby-instantclient

**Comment by ukolovda** [comment]
@tobiashm , it is fine, but Docker Hub have not 2.7.1 tags.
https://hub.docker.com/r/tobiashm/ruby-instantclient/tags?page=1&name=2.7.1
Some time ago 2.6.6 was created, but not 2.7.1

Thank you!

**Comment by tobiashm** [comment]
I'm sorry. It appears that something went wrong so a couple of images didn't get pushed.
I've pushed everything again, and checked that the tag exists now.

Notice also that the `2.7-…` tags are alias for the latest 2.7 release.

**Comment by ukolovda** [comment]
2.7.1 become available, thank you!
