### ISSUE TITLE
Ruby 3.2.0 with YJIT (UPD: Ruby 3.2.1 was released recently)

### ISSUE THREAD

**Issue by ukolovda** [tobiashm/ruby-instantclient#3]
Hello!

In the latest version of Ruby image was append `--YJIT` support (version from 13-JAN-2023):
```shell
$ docker run --rm ruby:3.2-slim ruby --yjit -e "puts 'ok'"
ok
```

But current version of ruby-instantclient have not it:
```shell
$ docker run --rm tobiashm/ruby-instantclient:3.2.0-21.8-basic ruby --yjit -e "puts 'ok'"
ruby: warning: Ruby was built without YJIT support. You may need to install rustc to build Ruby with YJIT.
ok
```

Can you rebuild images for 3.2* with latest Ruby base for YJIT support, please? YJIT give good performance boost and reduce CPU energy consume.

Thank you!

**Comment by ukolovda** [comment]
Hello!
Ruby 3.2.1 become be more actual now.
https://github.com/ruby/ruby/releases/tag/v3_2_1

Thank you!

**Comment by ukolovda** [comment]
Ruby 3.2.2 released.
https://www.ruby-lang.org/en/news/2023/03/30/ruby-3-2-2-released/

**Comment by tobiashm** [comment]
Hi @ukolovda 

I seem to have some issues with GitHub notifications, so I haven't seen you issue. Sorry.

There're new images up on hub.docker.com with Ruby 3.2.2 now.

**Comment by ukolovda** [comment]
> Hi @ukolovda
> 
> I seem to have some issues with GitHub notifications, so I haven't seen you issue. Sorry.
> 
> There're new images up on hub.docker.com with Ruby 3.2.2 now.

Thank you very much!
